mode: local

local:
  database_dev:
    url: mysql+asyncmy://root:${DB_PASSWORD}@localhost/bajkpaker_dev
  database_prod:
    url: mysql+asyncmy://root:${DB_PASSWORD}@localhost/bajkpaker_prod
deployment:
  database_dev:
    url: mysql+asyncmy://root:${DB_PASSWORD}@/bajkpaker_dev?unix_socket=/cloudsql/bajkpaker:europe-central2:bajkpaker-db
  database_prod:
    url: mysql+asyncmy://root:${DB_PASSWORD}@/bajkpaker_prod?unix_socket=/cloudsql/bajkpaker:europe-central2:bajkpaker-db