mode: local

local:
  database_dev:
    url: mysql+asyncmy://root:${DB_PASSWORD}@localhost/bajkpaker_dev
  database_prod:
    url: mysql+asyncmy://root:${DB_PASSWORD}@localhost/bajkpaker_prod
deployment:
  database_dev:
    url: mysql+asyncmy://root:${DB_PASSWORD}@bajkpaker-mysql.fly.dev/bajkpaker_dev
  database_prod:
    url: mysql+asyncmy://root:${DB_PASSWORD}@bajkpaker-mysql.fly.dev/bajkpaker_prod