# fly.toml app configuration file generated for bajkpaker on 2025-03-31T21:49:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bajkpaker'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
