version: '3.8'
services:
  product_service:
    build: ./backend/services/product_service
    container_name: product_service
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+asyncmy://root:Bartek11@db/bajkpaker_dev

  order_service:
    build: ./backend/services/order_service
    container_name: order_service
    ports:
      - "8002:8002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+asyncmy://root:Bartek11@db/bajkpaker_dev

  user_service:
    build: ./backend/services/user_service
    container_name: user_service
    ports:
      - "8003:8003"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+asyncmy://root:Bartek11@db/bajkpaker_dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - product_service
      - order_service
      - user_service

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Bartek11
      MYSQL_DATABASE: bajkpaker_dev
    ports:
      - "3306:3306"