apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: product-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mysql+asyncmy://root:Bartek11@db/bajkpaker_dev
          image: product-service
          name: product-service
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
