# fly.toml app configuration file generated for product-service on 2025-04-06T15:16:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-service'
primary_region = 'waw'

[build]

[env]
  ALLOWED_ORIGINS = 'https://bajkpaker.fly.dev'
  DB_ECHO = 'False'
  DB_HOST = 'bajkpaker-mysql.internal'
  DB_NAME = 'bajkpaker_dev'
  DB_PASSWORD = 'BajkPaker93.83'
  DB_PORT = '3306'
  DB_USER = 'bajkpaker'
  ENVIRONMENT = 'production'

[[mounts]]
  source = 'product_images'
  destination = '/app/static/images'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
