name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Run Black to automatically format the code
      - uses: psf/black@stable
        with:
          options: "--quiet"

      # Step 3: Check if there are any changes after Black has run
      - name: Check for changes
        run: |
          git diff --exit-code || echo "Code has been formatted."

      # Step 4: Commit and push the changes back to the repository if needed
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Black code formatting" || echo "No changes to commit."
          git push
